-- MySQL Script generated by MySQL Workbench
-- Thu May 15 10:55:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hoteldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoteldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoteldb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `hoteldb` ;


-- -----------------------------------------------------
-- Table `hoteldb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`user` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `role` ENUM('MANAGER', 'RECEPTIONIST', 'ACCOUNTANT','HOUSEKEEPER','SERVICESTAFF') NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `avatar` VARCHAR(100) NULL DEFAULT NULL,
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

ALTER TABLE user AUTO_INCREMENT = 1;
-- -----------------------------------------------------
-- Table `hoteldb`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`administrator` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `administrator_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `hoteldb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`customer_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`customer_type` (
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`customer` (
  `id` INT NULL DEFAULT NULL,
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `identification` VARCHAR(15) NULL DEFAULT NULL,
  `customer_type_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `identification` (`identification` ASC) VISIBLE,
  INDEX `customer_type_id` (`customer_type_id` ASC) VISIBLE,
  CONSTRAINT `customer_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `hoteldb`.`user` (`id`),
  CONSTRAINT `customer_ibfk_2`
    FOREIGN KEY (`customer_type_id`)
    REFERENCES `hoteldb`.`customer_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`room_type` (
  `name` VARCHAR(50) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`room` (
  `name` VARCHAR(50) NOT NULL,
  `image` VARCHAR(500) NOT NULL,
  `room_type_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  INDEX `room_type_id` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `room_ibfk_1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `hoteldb`.`room_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `hoteldb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`comment` (
  `customer_id` INT NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `room_id` INT NOT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `room_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `room_id` (`room_id` ASC) VISIBLE,
  CONSTRAINT `comment_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hoteldb`.`customer` (`id`),
  CONSTRAINT `comment_ibfk_2`
    FOREIGN KEY (`room_id`)
    REFERENCES `hoteldb`.`room` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`customer_type_regulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`customer_type_regulation` (
  `rate` FLOAT NOT NULL,
  `admin_id` INT NOT NULL,
  `customer_type_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `customer_type_id`),
  INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  INDEX `customer_type_id` (`customer_type_id` ASC) VISIBLE,
  CONSTRAINT `customer_type_regulation_ibfk_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `hoteldb`.`administrator` (`id`),
  CONSTRAINT `customer_type_regulation_ibfk_2`
    FOREIGN KEY (`customer_type_id`)
    REFERENCES `hoteldb`.`customer_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`receptionist` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `receptionist_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `hoteldb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`reservation` (
  `customer_id` INT NULL DEFAULT NULL,
  `receptionist_id` INT NULL DEFAULT NULL,
  `room_id` INT NOT NULL,
  `checkin_date` DATETIME NOT NULL,
  `checkout_date` DATETIME NOT NULL,
  `is_checkin` TINYINT(1) NULL DEFAULT NULL,
  `deposit` FLOAT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `receptionist_id` (`receptionist_id` ASC) VISIBLE,
  INDEX `room_id` (`room_id` ASC) VISIBLE,
  CONSTRAINT `reservation_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hoteldb`.`customer` (`customer_id`),
  CONSTRAINT `reservation_ibfk_2`
    FOREIGN KEY (`receptionist_id`)
    REFERENCES `hoteldb`.`receptionist` (`id`),
  CONSTRAINT `reservation_ibfk_3`
    FOREIGN KEY (`room_id`)
    REFERENCES `hoteldb`.`room` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`room_rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`room_rental` (
  `receptionist_id` INT NOT NULL,
  `room_id` INT NULL DEFAULT NULL,
  `reservation_id` INT NULL DEFAULT NULL,
  `checkin_date` DATETIME NULL DEFAULT NULL,
  `checkout_date` DATETIME NULL DEFAULT NULL,
  `deposit` FLOAT NULL DEFAULT NULL,
  `is_paid` TINYINT(1) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `receptionist_id` (`receptionist_id` ASC) VISIBLE,
  INDEX `room_id` (`room_id` ASC) VISIBLE,
  INDEX `reservation_id` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `room_rental_ibfk_1`
    FOREIGN KEY (`receptionist_id`)
    REFERENCES `hoteldb`.`receptionist` (`id`),
  CONSTRAINT `room_rental_ibfk_2`
    FOREIGN KEY (`room_id`)
    REFERENCES `hoteldb`.`room` (`id`),
  CONSTRAINT `room_rental_ibfk_3`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `hoteldb`.`reservation` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`receipt`
-- -----------------------------------------------------
drop table receipt;
CREATE TABLE IF NOT EXISTS hoteldb.receipt (
    id INT NOT NULL AUTO_INCREMENT,
    receptionist_id INT NOT NULL,  -- Nhân viên tạo hóa đơn
    rental_room_id INT NOT NULL,   -- Phòng thuê tương ứng
    total_price FLOAT NOT NULL,    -- Tổng tiền phòng + dịch vụ
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payment_method ENUM('CASH', 'CARD', 'TRANSFER', 'OTHER') NOT NULL,

    PRIMARY KEY (id),
    INDEX (receptionist_id),
    INDEX (rental_room_id),

    CONSTRAINT receipt_ibfk_1 FOREIGN KEY (receptionist_id) REFERENCES hoteldb.receptionist (id),
    CONSTRAINT receipt_ibfk_2 FOREIGN KEY (rental_room_id) REFERENCES hoteldb.room_rental (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- Ghi các dịch vụ khách dùng trong quá trình thuê phòng
CREATE TABLE IF NOT EXISTS hoteldb.room_service (
    id INT NOT NULL AUTO_INCREMENT,
    room_rental_id INT NOT NULL,   -- Liên kết đến lượt thuê phòng
    service_id INT NOT NULL,       -- Dịch vụ đã dùng
    quantity INT NOT NULL DEFAULT 1,
    total_price FLOAT NOT NULL,    -- Tổng tiền = đơn giá * số lượng

    PRIMARY KEY (id),
    INDEX (room_rental_id),
    INDEX (service_id),

    CONSTRAINT room_service_ibfk_1 FOREIGN KEY (room_rental_id) REFERENCES hoteldb.room_rental (id),
    CONSTRAINT room_service_ibfk_2 FOREIGN KEY (service_id) REFERENCES hoteldb.service (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`reservation_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`reservation_detail` (
  `customer_id` INT NOT NULL,
  `reservation_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `customer_id`, `reservation_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `reservation_id` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `reservation_detail_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hoteldb`.`customer` (`customer_id`),
  CONSTRAINT `reservation_detail_ibfk_2`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `hoteldb`.`reservation` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`room_regulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`room_regulation` (
  `room_type_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `room_quantity` INT NULL DEFAULT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `surcharge` FLOAT NULL DEFAULT NULL,
  `deposit_rate` FLOAT NULL DEFAULT NULL,
  `distance` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `room_type_id`),
  INDEX `room_type_id` (`room_type_id` ASC) VISIBLE,
  INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `room_regulation_ibfk_1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `hoteldb`.`room_type` (`id`),
  CONSTRAINT `room_regulation_ibfk_2`
    FOREIGN KEY (`admin_id`)
    REFERENCES `hoteldb`.`administrator` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hoteldb`.`room_rental_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`room_rental_detail` (
  `customer_id` INT NOT NULL,
  `room_rental_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `customer_id`, `room_rental_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `room_rental_id` (`room_rental_id` ASC) VISIBLE,
  CONSTRAINT `room_rental_detail_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hoteldb`.`customer` (`customer_id`),
  CONSTRAINT `room_rental_detail_ibfk_2`
    FOREIGN KEY (`room_rental_id`)
    REFERENCES `hoteldb`.`room_rental` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS hoteldb.service (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,         -- e.g., 'Spa', 'Laundry'
    price FLOAT NOT NULL,
    description VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX name (name ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;




CREATE TABLE IF NOT EXISTS hoteldb.report (
    id INT NOT NULL AUTO_INCREMENT,
    admin_id INT NOT NULL,
    created_date DATETIME NOT NULL,
    total_revenue FLOAT NOT NULL,
    description VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX admin_id (admin_id ASC),
    CONSTRAINT report_ibfk_1 FOREIGN KEY (admin_id) REFERENCES hoteldb.administrator (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hoteldb.housekeeping_task (
    id INT NOT NULL AUTO_INCREMENT,
    housekeeper_id INT NOT NULL,
    room_id INT NOT NULL,
    rental_id INT NOT NULL,
    assigned_date DATETIME NOT NULL,
    completed_date DATETIME DEFAULT NULL,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    notes VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX housekeeper_id (housekeeper_id ASC),
    INDEX room_id (room_id ASC),
    INDEX rental_id (rental_id ASC),
    CONSTRAINT housekeeping_task_ibfk_1 FOREIGN KEY (housekeeper_id) REFERENCES hoteldb.user (id),
    CONSTRAINT housekeeping_task_ibfk_2 FOREIGN KEY (room_id) REFERENCES hoteldb.room (id),
    CONSTRAINT housekeeping_task_ibfk_3 FOREIGN KEY (rental_id) REFERENCES hoteldb.room_rental (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS hoteldb.activity_log (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    action_type VARCHAR(100) NOT NULL,        -- e.g., 'BOOK_ROOM', 'CHECKOUT', 'PAYMENT'
    action_description VARCHAR(500) DEFAULT NULL,
    action_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX user_id (user_id ASC),
    CONSTRAINT activity_log_ibfk_1 FOREIGN KEY (user_id) REFERENCES hoteldb.user (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE OR REPLACE VIEW hoteldb.available_room AS
SELECT 
    r.id AS room_id,
    r.name AS room_name,
    rt.name AS room_type,
    r.image
FROM hoteldb.room r
JOIN hoteldb.room_type rt ON r.room_type_id = rt.id
WHERE r.id NOT IN (
    SELECT room_id
    FROM hoteldb.room_rental
    WHERE checkout_date IS NULL OR is_paid = 0
);

CREATE OR REPLACE VIEW hoteldb.employeelist AS
SELECT 
    id AS user_id,
    username,
    role,
    email,
    phone,
    gender,
    avatar
FROM hoteldb.user
WHERE role IN ('MANAGER', 'RECEPTIONIST', 'ACCOUNTANT', 'HOUSEKEEPER', 'SERVICESTAFF');

CREATE OR REPLACE VIEW hoteldb.guesthistory AS
SELECT 
    c.customer_id,
    c.name AS customer_name,
    rr.id AS rental_id,
    rr.checkin_date,
    rr.checkout_date,
    ro.name AS room_name
FROM hoteldb.customer c
JOIN hoteldb.room_rental_detail rd ON c.customer_id = rd.customer_id
JOIN hoteldb.room_rental rr ON rd.room_rental_id = rr.id
JOIN hoteldb.room ro ON rr.room_id = ro.id;


CREATE OR REPLACE VIEW hoteldb.reportlist AS
SELECT 
    rp.id AS report_id,
    u.username AS admin_username,
    rp.created_date,
    rp.total_revenue,
    rp.description
FROM hoteldb.report rp
JOIN hoteldb.administrator a ON rp.admin_id = a.id
JOIN hoteldb.user u ON a.id = u.id;
CREATE OR REPLACE VIEW hoteldb.systemchangelogs AS
SELECT 
    al.id AS log_id,
    u.username,
    al.action_type,
    al.action_description,
    al.action_time
FROM hoteldb.activity_log al
JOIN hoteldb.user u ON al.user_id = u.id
ORDER BY al.action_time DESC;



